version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    branches:
      only:
      - graphene
    working_directory: ~/go/src/github.com/quantadex/distributed_quanta_bridge
    environment:
      GOPATH: ~/go
    steps:
    - run:
        name: Install checkout requirements
        command: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install
    - run: go get -u github.com/tebeka/go2xunit
    - checkout
    - run:
        name: Checkout binaries
        command: git lfs pull
    - run: ls -a && pwd
    - run: tar xvf vendor.tar
    - run: mkdir -p reports
    - run:
        name: Install Docker Compose
        command: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
    - run: cd blockchain && docker-compose up -d
    - run: go test -v ./node/...

#    - run: cd $BUILD_PATH && godep go test ./..
#    - run:
#        name: run_test
#        command: |
#          for name in common node registrar trust; do
#              echo "Testing $name..."
#              rm -f ./reports/report_$name.xml
#              2>&1 go test -v ./$name/... | tee gotest_$name.out
#              $GOPATH/bin/go2xunit -fail -input gotest_$name.out -output ./reports/report_$name.xml || :
#              echo
#          done
    - store_test_results:
        path: ./reports
    - store_artifacts:
        path: ./reports