package kv_store

const PENDING_QUANTA_TX = "PENDING_QUANTA_TX"
const COMPLETED_QUANTA_TX = "COMPLETED_QUANTA_TX"
const ETH_TX_LOG = "ETH_TX_LOG"
const ETH_TX_LOG_SIGNED = "ETH_TX_LOG_SIGNED"
const ETH_TX_LOG_SUBMITTED = "ETH_TX_LOG_SUBMITTED"
const ETH_TX_LOG_FAILED_RECOVERABLE = "ETH_TX_LOG_FAILED_RECOVERABLE"
const ETH_TX_LOG_FAILED_UNRECOVERABLE = "ETH_TX_LOG_FAILED_UNRECOVERABLE"
const ETH_TX_LOG_RETRY = "ETH_TX_LOG_RETRY"
