ListenIp: 0.0.0.0
ListenPort: 5000
UsePrevKeys: true
KvDbName: ./data/node1
CoinName: ETH
IssuerAddress: QBU734ICFLPITA6IYTZCUJEQWLIOV2R5DHVCAXGJ4AB4XMBTMM4MSB7P
NodeKey: ZDFTL63XHTY7XMLQHKW22TGVGBHNKTZQTWK7N3HZCPLDCTNN63T2BJFB
HorizonUrl: http://testnet-02.quantachain.io:8000/
NetworkPassphrase: QUANTA Test Network ; September 2018
RegistrarIp: 0.0.0.0
RegistrarPort: 5100
EthereumNetworkId: 15
EthereumBlockStart: 5
EthereumRpc: http://localhost:7545
EthereumKeyStore: c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
EthereumTrustAddr: 0xf328c11c4df88d18fcbd30ad38d8b4714f4b33bf
HEALTH_INTERVAL: 5
DatabaseUrl: postgres://postgres:@localhost/crosschain_3
