FilterTransferEventListenIp: 0.0.0.0
ListenPort: 5001
UsePrevKeys: true
KvDbName: kv_db_5100
CoinName: ETH
IssuerAddress: QAHXFPFJ33VV4C4BTXECIQCNI7CXRKA6KKG5FP3TJFNWGE7YUC4MBNFB
NodeKey: ZBYEUJIWP2AXG2V6ZW4F5OTM5APW3SOTTM6YGMKO6MQSY7U3IHFJZHWQ
HorizonUrl: http://testnet-02.quantachain.io:8000/
NetworkPassphrase: QUANTA Test Network ; September 2018
RegistrarIp: localhost
RegistrarPort: 5001
EthereumNetworkId: 3
EthereumBlockStart: 0
EthereumRpc: https://ropsten.infura.io/v3/7b880b2fb55c454985d1c1540f47cbf6
EthereumKeyStore: A7D7C6A92361590650AD0965970E186179F24F36B2B51CFE83F3AE8886BB6773
EthereumTrustAddr: 0xBD770336fF47A3B61D4f54cc0Fb541Ea7baAE92d
HEALTH_INTERVAL: 5