package queue

const HEALTH_QUEUE = "HEALTH_QUEUE"
const PEERMSG_QUEUE = "PEERMSG_QUEUE"
const MANIFEST_QUEUE = "MANIFEST_QUEUE"
const QUANTA_TX_QUEUE = "QUANTA_TX_QUEUE"
const REFUNDMSG_QUEUE = "REFUNDMSG_QUEUE"
const ADDR_MSG_QUEUE = "ADDR_MSG_QUEUE"
