ganache:
	ganache-cli -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" -a 3 --gasLimit 0x2FEFD800000 --defaultBalanceEther 10000
console:
	truffle console
debugger:
	truffle develop --log
compile:
	truffle compile

.PHONY:
test: .PHONY
	truffle test
migrate:
	truffle migrate
abi:
	truffle-export-abi
